### ISSUE TITLE
[Bug]: jobs abort problem

### ISSUE THREAD

**Issue by KE4NaS** [openbullet/OpenBullet2#1037]
### Version of the software

0.3.0

### Operating system

Windows 10

### Browser / Native

Chrome 126

### What happened?

when you stop and then press abort or force abort the job marks that line of code in the wordlist as checked and when you start the jobs to continue the check it skips the aborted lines, you can solve it so that when the job starts it checks the Aborted lines of the loaded wordlist because it was not checked?

**Comment by openbullet** [comment]
You can tick an option to mark the lines as "To Check" upon abort, you can find it in the Multi Run Job options. Apart from this, you can rewind the skip to make it check the lines that were not checked before. At this point in time, I do not plan to add a way to keep track of aborted lines between different runs, since the skip can be modified and it would mess with this system.
