### ISSUE TITLE
Wordlist keeps being used when using random string as data. 

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#1096]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

If you have a wordlist chosen in the edit page and you decide to switch and use  the Random string block as your username and password login openbullet still uses your wordlist and counts down. 

### Reproduction steps

Start OB2 create a random string block and use it as your data and go to edit page and choose wordlist. 

### What is the current bug behavior?

It uses  the world list and counts down. I checked though it’s not using the data from the word list but it still counts down and stops the config when the wordlist is complete. 

### What is the expected correct behavior?

The behavior should be not to use the wordlist and switch over to infinite.  Or is there a code we can put in the config to switch over to Infinite when random string block has been activated to be used as login and password. 
 

### Version of the client

Lates version web client 031

### Type of client

Web client

### Environment

```markdown
- OS:windows 11 
- Virtualization:
- Browser:opera
```

**Comment by openbullet** [comment]
A config cannot control the job's data pool, sorry. If you want to use random strings you can do one of these:
- generate your own custom wordlist with random data
- use the combinations data pool (to make sure you don't check the same data twice and cover all possibilities)
- use the infinite data pool and generate your random string directly inside the config's code, then replace `data.Line.Data` with that value

I will not add the ability to control a job's settings from within a config, since that would be extremely hard to do while running.
