### ISSUE TITLE
[BUG] Creating a Utility Files Block With An Empty Input Causes  LoliCodeParsingExpection

### ISSUE THREAD

**Issue by bypassLife** [openbullet/OpenBullet2#141]
**Describe the bug**
Creating a Utility Files Block With An Empty Input Causes  LoliCodeParsingExpection
**To Reproduce**
1. Create a Utility Files block
2. Click on lolicode
3. Try switching back to stacker

**Expected behavior**
An empty input no error
**Screenshots**

https://i.imgur.com/x4hLQxi.png
https://i.imgur.com/FDIqEuJ.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by openbullet** [comment]
I decided that this behaviour is correct, the LoliCode parser should in fact throw an error if this happens because the config cannot be compiled to C# if the variable name is left empty. It's easy to fix as the parser informs the user about which setting is giving problems and the user can simply add some letters after the `@` to make it work.
