### ISSUE TITLE
[REQUEST] Combine Updater With Program

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#150]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Combine the Updater with the Program.
A single .exe file.
Will check for updates and after it's finished checking/updating it will run the program.

**Describe alternatives you've considered**
Creating a .bat file.

**Comment by openbullet** [comment]
This is too hard to do, because I have to:
- Add a way to make OB2 launch a separate process and shut itself down (OB2 cannot update its own files while it's using them)
- Let that process update OB2 files
- Launch OB2 again and reattach to the original terminal

Challenges that I will face when starting processes with code:
- How to launch the program? We could use something like `dotnet ./Program.dll` to have the same command across all operating systems but what if the user doesn't have `dotnet` in the path? What if it requires sudo permissions? This is too hard to do in a non self-contained application (as it currently depends on the framework)
- How to reattach OB2 to the terminal where it was first launched?

Remember OB2 is cross platform not windows-only. This wouldn't be too hard if OB2 was windows-only but it's not.
I don't plan to do something like this anytime soon, sorry.
