### ISSUE TITLE
[BUG] Job Errors

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#154]
**Describe the bug**
Doesn't matter which config I run with the job I get high amount of errors.
I don't get a single error when testing the config, but when starting a job with the same config I get many errors.

**To Reproduce**
1. Start any job with any config.
2. See "Errors" count.

**Expected behavior**
Error count should be minimal.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Chrome
 - Version 0.1.8

**Comment by openbullet** [comment]
This is not a bug. The "Errors" you're seeing just mean that there were exceptions while executing the code, which 99% of the times are due to the HttpRequest block paired with bad or non-working proxies. The `ERROR` status is treated as `BAN` so you shouldn't worry too much about that, unless you have a proxiless config.
