### ISSUE TITLE
Add variable option in custom input

### ISSUE THREAD

**Issue by ep5tein** [openbullet/OpenBullet2#172]
Hi, back in OB1 it was possible to put variable in customs input, I tried in OB2 but the variable is not proceeded.
It it can be good to let choice between text and interpolated string option like in stacker:
![image](https://user-images.githubusercontent.com/80283138/112373622-7695ef80-8ce1-11eb-99e5-83993e83fe03.png)

![image](https://user-images.githubusercontent.com/80283138/112373144-eb1c5e80-8ce0-11eb-8620-e4fe17f50da9.png)

**Comment by openbullet** [comment]
I honestly don't know if this is feasible to be honest, but if it is, it would require a lot of work. So I'm making this as low priority.

**Comment by openbullet** [comment]
Sorry I'm closing this as I will probably never do it. It's better if you do something like this
1. The user enters `Hello, $USERNAME$ how are you?`
2. You use the replace block to replace `$USERNAME$` with the value of `input.USERNAME` (passed as variable)

Of course it only works for predefined variables, but since the names of variables are most likely predefined in a config, you can know them in advance and just do multiple replaces.
