### ISSUE TITLE
Cyrillic Brocken

### ISSUE THREAD

**Issue by RiseFox** [openbullet/OpenBullet2#23]
After some tests, found a problem with Cyrillic in requests

![photo_2021-03-09_18-25-24](https://user-images.githubusercontent.com/28965614/110503544-f9755280-8104-11eb-8d8e-1280dd9e5937.jpg)

**Comment by openbullet** [comment]
Just a note for myself when I implement this, windows-1251 encoding is not supported in .NET core so we need to add a nuget package.
https://stackoverflow.com/questions/32471058/windows-1252-is-not-supported-encoding-name
We also want to detect the charset from the response of the server and use the correct encoding instead of being fixed to UTF-8.

**Comment by RiseFox** [comment]
Found this https://stackoverflow.com/questions/37870084/net-core-doesnt-know-about-windows-1252-how-to-fix
Tomorrow I'll free, and try to build it like a addon for ob2 or something else, and second problem, ob2 make error when working with xml, will be open issue tomorrow, so tired (

**Comment by openbullet** [comment]
@RiseFox don't try this issue, it's pretty hard, I will handle it myself. A lot can go wrong here.

**Comment by RiseFox** [comment]
The problem site filmix<dot>ac

**Comment by openbullet** [comment]
@RiseFox you can PM me on the forum https://discourse.openbullet.dev

**Comment by mastercho** [comment]
I can confirm that issue exist on my side too

**Comment by RiseFox** [comment]
@openbullet I have some idea, when i know, the site with windows-1251, then i have a checkbox with
`var windows1251 = Encoding.GetEncoding("windows-1251");
var utf8 = Encoding.UTF8;

var originalBytes = windows1251.GetBytes(document.ToString());
var correctXmlString = utf8.GetString(originalBytes);
var correctDocument = XDocument.Parse(correctXmlString);`

or something like this:
`string text = "Р—Р°РєР°Р· Р·РІРѕРЅРєР° С‚РµС…РЅРёС‡РµСЃРєРѕР№ РїРѕРґРґРµСЂР¶РєРё";

Encoding utf8 = Encoding.GetEncoding("UTF-8");
Encoding win1251 = Encoding.GetEncoding("Windows-1251");

byte[] utf8Bytes = win1251.GetBytes(text);
byte[] win1251Bytes = Encoding.Convert(utf8, win1251, utf8Bytes);`

**Comment by openbullet** [comment]
@RiseFox a textbox would be better than a checkbox (to support multiple encodings and not just 1), but the problem is that there is no native support for `windows-1251` encoding in .NET 5, it was only in .NET framework, so we need to use the library that you linked above in order to do it. Anyways your solution seems better than automatically detecting it, so I'm probably going to do what you suggested ^_^

**Comment by openbullet** [comment]
Done, you can now write `windows-1251` in the Code Pages Encoding textbox of the Http Request block
