### ISSUE TITLE
Remoto config issue

### ISSUE THREAD

**Issue by kurosaki-88** [openbullet/OpenBullet2#24]
if they put in job a cfg in remote our
and close ob2
when you reopen it disappears in the job
and if you go to open the job setting
it always gives reload
you have to physically delete the old job first and recreate it

**Comment by openbullet** [comment]
What he means is that when you have a job that is using a remote config (from an API endpoint, shared by another OB2 instance) and then restart OB2, it will throw an exception. This is probably due to the fact that it cannot find the config anymore, we should add a failsafe so that if the config id is null or not found it won't crash everything but just unset the config in the job.

**Comment by openbullet** [comment]
Should be fixed by https://github.com/openbullet/OpenBullet2/commit/9500cc66734d24c18d54d46dfa64e2c3d6241e27 please let me know and close the issue if solved

**Comment by kurosaki-88** [comment]
great job!
