### ISSUE TITLE
cant uploade configs

### ISSUE THREAD

**Issue by MaximalMax07** [openbullet/OpenBullet2#260]
If i try to upload a config, it says invalid data expeption

**Comment by openbullet** [comment]
Just to know, in what format are the configs you're trying to upload? What's their file extension?

**Comment by openbullet** [comment]
OB2 only supports .opk configs, you're probably trying to upload a .loli config or something for OB1 or modded versions of OB1.

**Comment by kerrykerry611** [comment]
Then how do we convert the .loli to .opk file please

**Comment by openbullet** [comment]
@kerrykerry611 place the .loli configs in the `UserData/Configs` folder of OB2 and then click on the Reload button in the Configs page, it will repack them into `.opk` format (they will still have the old LoliScript inside, you will be able to run them and edit them with bare LoliScript but you will not be able to use stacker or any of the new blocks / features of OB2).

**Comment by shhahid7** [comment]
how to convert opk -> loli ?

**Comment by frozen905** [comment]
I uploaded a .loli but nothing works properly, I'm guessing these aren't backwards compatible typically?  It's not even prompting me for URL or anything when I try to use the step by step

**Comment by openbullet** [comment]
> I uploaded a .loli but nothing works properly, I'm guessing these aren't backwards compatible typically? It's not even prompting me for URL or anything when I try to use the step by step

A couple of things:
1. Make sure to check out the wordlist type, as it might be not configured properly in your `Environment.ini` file. OB1 and OB2 might have different defaults, so maybe that is why it's not working. [Here](https://docs.openbullet.dev/docs/wordlists/general-info) are some helpful docs.
2. In OB2, when using custom inputs, there are no more prompts while debugging, so if you want to test a value you either have to override it manually in your script (e.g., in LoliCode just write `input.YOUR_INPUT = "abc"` or use a Constant String block with output variable set to `input.YOUR_INPUT`), or use the "Default Answer" box in the config settings, under the "Inputs" section. I decided to remove it because it was getting extremely annoying since you had to insert the custom input answer every single time you ran the debugger. Maybe I will add an easier way to define custom inputs while debugging. Please open an issue for this if you're interested.

Finally, not EVERY single feature is backwards compatible, you can find a list of unsupported features [here](https://docs.openbullet.dev/docs/faq), although I expect 99% of OB1 configs to not have any trouble when imported in OB2, most errors are due to the wordlist types being different.
