### ISSUE TITLE
[REQUEST] Compile DataRule Regex

### ISSUE THREAD

**Issue by Itamai** [openbullet/OpenBullet2#262]
Performance depends how often the regex match method is called and also how precise the regex is but in general this should perform better.

**Comment by openbullet** [comment]
I did some research, and I found that the Regex engine in C# already caches regular expressions https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.ismatch?view=net-5.0

I cannot use the Compiled flag (which compiles a regex to the assembly) since they are specified at runtime and not known at compile time.
