### ISSUE TITLE
[REQUEST] add support for floating point values

### ISSUE THREAD

**Issue by crazygamer96** [openbullet/OpenBullet2#319]
Currently I am trying to sort a list of multiple constant strings that I want to sort by the Price but there is other numbers in front of it that would mess it up:
![image](https://user-images.githubusercontent.com/33612551/122276994-3be3c380-ce9a-11eb-9ac8-021dc4abb0a9.png)
that is what it sends to discord but I want it to be sorted like this: 
![image](https://user-images.githubusercontent.com/33612551/122277153-6d5c8f00-ce9a-11eb-80e7-8ffa057f2985.png)
Not sure if when you sort it you can make it sort them by making it start at a different point in every line if that makes sense

**Comment by openbullet** [comment]
I don't think I can add something to do this, I'll give you a piece of code that will get the job done but I'm not going to add any blocks because it would be extremely hard to do for the generic case.

https://discourse.openbullet.dev/t/sorting-a-list-of-strings-basing-on-numbers-inside-the-elements/3041
