### ISSUE TITLE
My OB2 is saving bad hits as NONE on the hits tab

### ISSUE THREAD

**Issue by DevTMs** [openbullet/OpenBullet2#327]
Hello Folks !

I would like to know how to avoid getting bad hits saved on the HITS tab ? 

Thank you !

![image](https://user-images.githubusercontent.com/38444394/123036577-99719600-d3ed-11eb-8bb6-44ee7968fca0.png)

**Comment by openbullet** [comment]
Easy fix: go to config settings and put the ban loop evasion to 0.

Explanation for the behaviour:
Those are the lines that were banned more than 100 times and hence were marked as TO CHECK. You should look into them because you're probably missing some keys in your keycheck, that's the purpose of ban loop evasion. Turn on the bot log in RL Settings and look at their full log after you get them in a job, so you can spot what went wrong (100 BANs means it's not a proxy issue but most definitely some missing keys in the keycheck).
