### ISSUE TITLE
Local link for file system hits

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#388]
If a job is saving hits to File System, it would be nice to make the bold part a clickable link that opens the local path to the Hits folder where it saves the hits.
Hit outputs: File system (**UserData/Hits**)

**Comment by openbullet** [comment]
It's not possible to interact with a file manager from within the browser for security reasons. This will be possible in the native application though. I'm going to close this for now as there is no such application yet.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
@openbullet 
![image](https://user-images.githubusercontent.com/41063376/147989128-f9359616-b081-469b-8535-dc678fecda38.png)
you can you run a command, but can't you open a folder?
idk is this is possible in Linux, but please do this for windows and maybe macOS

```
// for Windows
BLOCK:ShellCommand
  executable = "\"C:\\Windows\\explorer.exe\" \"C:\\Program Files\""
  => VAR @shellCommandOutput
ENDBLOCK
```

**Comment by openbullet** [comment]
You're doing it wrong.
Executable should be `C:/Windows/explorer.exe`
Arguments should be `"C:/Program Files/"` because the folder to open is an argument passed to the executable so it goes in the second field

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
Yes, it was wrong but it worked
important question is that "are you going to reopen this issue?"
@openbullet

**Comment by openbullet** [comment]
No I'm not going to reopen this because there is nothing to fix, it already works as intended.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
@openbullet 
yes, there is no problem with 'Shell Command'
and this issue is not about that too

![image](https://user-images.githubusercontent.com/41063376/148450905-5ceec4c4-69ba-462d-9ba2-018d03dd17e7.png)
This issue is asking you to make this like clickable, that we can access Hits folder easily
you said that you can't do this because of browser limits
i said that if you can open a folder in file manager of any OS using 'Shell Commands'-
then you can make that line to open Hits folder without any problems

when that path clicked, run a command to open file manage

**Comment by openbullet** [comment]
You can open the folder on the server where OB2 is running, yes, but who is telling you that OB2 is running on localhost? What if it is running on another person's server? Also doing this would require to use `Process.Start` which should work cross platform https://stackoverflow.com/questions/1132422/open-a-folder-using-process-start but since the folder name is supplied by the end user (and not by the server owner) this will cause a vulnerability where any user will be able to execute arbitrary shell commands on the server.

Keep in mind OB2 is not localhost-only and introducing something like this can be very risky. That's why I said it only makes sense to do this in the native application. Now, if you want me to implement this on the native application, that's possible and I can reopen the issue, in the other case sorry but unless someone suggests a better cross-platform approach to open a folder with no possible exploits, I cannot do it.
