### ISSUE TITLE
[Bug]: Blazor and https in linux

### ISSUE THREAD

**Issue by Meliio** [openbullet/OpenBullet2#411]
### Version of the software

0.1.21

### Operating system

linux raspi os lite

### Browser

edge or chrome

### What happened?

I can’t access OB2 in https only http see [screen](https://ibb.co/H7d47Dk)

for the installation I followed this [tuto](https://www.youtube.com/watch?v=P5PwM0npy7E)

idea: https://github.com/dotnet/aspnetcore/issues/28237

**Comment by JReming85** [comment]
Did you change http to https and https redirect in the configs.

OpenBulletSettings.json - HttpsRedirect
appsettings.Release.json - https://0.0.0.0:5000

Personally I would recommend  leaving it all as default with it set to http://127.0.0.1:5000 and setup a reverse proxy using apache/nginx

**Comment by openbullet** [comment]
You can use a reverse proxy like nginx as @JReming85 suggested. I have already successfully set up https for Blazor Server in the past and I can add a simple way to add a certificate. Are you interested in hosting OB2 on an actual domain or would you just like to access via HTTPS locally on your machine? Because in that case a self-signed certificate would be enough. I will make a guide to configure HTTPS as soon as I have some time.

**Comment by openbullet** [comment]
You can follow this guide to set up HTTPS directly on the blazor server without using a reverse proxy.
https://discourse.openbullet.dev/t/how-to-set-up-https-in-openbullet-2/4345
