### ISSUE TITLE
[REQUEST] Multiple Header Key with Same Name

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/OpenBullet2#416]
To bypass a protection i need to send something like this
![image](https://user-images.githubusercontent.com/41063376/129985940-8e2074f5-4ee1-4a9d-b5fe-48f945a3c7ef.png)
but OB2 removes one of them before start

**Comment by openbullet** [comment]
You are not allowed to have multiple headers with the same key as of now since they are stored as a dictionary. In those specific cases you should look into sending a raw HTTP request with the TCP block so that you can fully configure exactly what is sent.

**Comment by Cyber-Criminal** [comment]
can't do that using C# in OB2?

**Comment by Cyber-Criminal** [comment]
'raw HTTP request with the TCP block' seems not easy

**Comment by openbullet** [comment]
No you cannot do it in C# because RuriLib.Http (the library I wrote for Http-related stuff) accepts a dictionary for headers. You could use the standard HttpClient that .NET provides (which accepts multiple values for headers) but they are probably going to get serialized with a comma between the values and also you lose the ability to use SOCKS proxies and you have to manually do the requests yourself.

I suggest writing the raw request as I told you. Simply take the entire request from the log, copy it, replace newline with `\r\n` and paste its content in a TCP Http Send Read block (after a TCP Connect block). If you are struggling feel free to tell me and I will provide an example.
