### ISSUE TITLE
[REQUEST] Clean Wordlists with regex

### ISSUE THREAD

**Issue by theamericans47** [openbullet/OpenBullet2#419]
Is it possible to add an option to clean a wordlist with regex : delete all lines which don't match a regex expression, before or after uploading ?

**Comment by openbullet** [comment]
There are plenty of external tools to do this, OB2 does not want to be a wordlist editor. Also you can set up a regex in the Environment.ini file so that invalid lines are skipped and marked as invalid, so OB2 can already detect badly formatted lines, just look into wordlist types and Environment.ini
