### ISSUE TITLE
[Bug]: Failed to use proxies with Authentication

### ISSUE THREAD

**Issue by shinkuan** [openbullet/OpenBullet2#421]
### Version of the software

0.1.21

### Operating system

Windows 10

### Browser

Brave

### What happened?

When I tried to use a proxy with auth in config test, it showed:
```
ProxyException
[Executing block LOGIN] The proxy didn't reply with 200 OK
```
![PXY](https://user-images.githubusercontent.com/35415788/130248275-1bbc3254-230e-4f04-9e9c-0dda78232a46.PNG)

But I'm 100% sure the proxy is working. (The format was IP:PORT:USERNAME:PASSWORD)
I'm using luminati proxies which looks like this
`zproxy.lum-superproxy.io:22225:lum-customer-USERNAME-zone-ZONE:PASSWORD`

However, proxy checker Job shows all the proxies are working.
![WPXY](https://user-images.githubusercontent.com/35415788/130249224-0484e26f-f0b7-4b6d-a2ab-0b568f5e8450.png)

**Comment by JReming85** [comment]
Personally never had an issue with auth proxies both Socks5 and HTTP

**Comment by openbullet** [comment]
Please email me a proxy to test this on at `ruri (at) openbullet [dot] dev`

**Comment by DismotionSoft** [comment]
Facing the same issue. When testing the proxies in the jobs tab, everything is marked as working. When testing on a config/stacker "The proxy didn't reply with 200 OK" error is returned @openbullet

**Comment by openbullet** [comment]
@DismotionSoft please send me the proxy via email at the address above

**Comment by JReming85** [comment]
What response code was returned if it wasnt a 200?

**Comment by openbullet** [comment]
Usually if the proxy doesn't reply with 200 OK it replies with 401 or 403 meaning that the credentials are wrong (or didn't get sent properly).

**Comment by JReming85** [comment]
Well 401 could also be on the websites end as well.. not authorized to view the page and 403 would be forbidden.

429 would be blocked by rate limiting

**Comment by openbullet** [comment]
No you're not understanding. When dealing with HTTP proxies, we need to send a Connect request to the proxy so it will redirect all our data for us, so we send this Connect request and it will reply to us with 200 OK if it accepts to set up a tunnel for our data to reach the website, otherwise it will send a 4xx status code.

This is done when connecting to an HTTP(S) proxy, BEFORE any website is called via that proxy. For SOCKS proxies there's a different protocol and the connection request is not done via HTTP so this error message only appears when dealing with HTTP proxies.

**Comment by openbullet** [comment]
Should be solved with https://github.com/openbullet/OpenBullet2/pull/481
If not reopen after 0.1.25 is out
