### ISSUE TITLE
[REQUEST] search at debugger & remote proxy

### ISSUE THREAD

**Issue by walpak1** [openbullet/OpenBullet2#448]
please add this
https://i.imgur.com/0Ru2bfS.png
https://i.imgur.com/6WdiChm.png

**Comment by openbullet** [comment]
Search was already requested here https://github.com/openbullet/OpenBullet2/issues/437
The remote proxies are configurable in job option > proxy sources > remote. They are configurable per-job instead of globally to give more granularity. If you don't want to keep copying them when you make new jobs you can simply CLONE an existing job with the relative button.
