### ISSUE TITLE
[Bug]: HTTP Proxy - SSL Connect/Timed Out Waiting for data errors

### ISSUE THREAD

**Issue by JReming85** [openbullet/OpenBullet2#488]
### Version of the software

0.1.25

### Operating system

Microsoft Windows NT 6.2.9200.0 | Server 2012 DC

### Browser / Native

Chrome 91 / Opera 77.0.4054.203

### What happened?

Carried over from forum post https://discourse.openbullet.dev/t/ssl-connect-problem/2060/12

Issue:
Since updating to 0.1.25, certain HTTP proxies that used to work on 0.1.23 no longer work and give either Failed SSL connect errors or Timed out waiting for data errors

**Comment by openbullet** [comment]
Just for future reference, the issue arose due to this PR which causes `\r\n` to be written 3 times instead of 2 for proxies without credentials.
https://github.com/openbullet/OpenBullet2/pull/481

I fixed it on the proxy-fix branch, waiting for confirmation from the user and I will merge it to master.

**Comment by openbullet** [comment]
Merged
