### ISSUE TITLE
[REQUEST] Custom Inputs

### ISSUE THREAD

**Issue by Swirlon** [openbullet/OpenBullet2#49]
**Make debugger ask for inputs every time**

**Comment by openbullet** [comment]
I would like to discuss this a little bit, because it's super annoying to have 1 or maybe 3 boxes pop up EACH time you run the debugger. Right now it's programmed to take the default answer that you configured and use that one as the value for the custom input. Is there really a need to implement this or can we keep using the current system?

**Comment by openbullet** [comment]
Closing this as I don't plan to implement it, read above to know how to do it
