### ISSUE TITLE
[REQUEST] Limit the Suggested Bots and CPM to the minimum

### ISSUE THREAD

**Issue by atayseny** [openbullet/OpenBullet2#490]
Hello, thank you for your effort in creating this tool.

My humble request is, you, as a software OWNER, PLEASE, limit the Suggested Bots to 1 and Maximum CPM to 3, otherwise you would be contributing to the appearance of new and better systems of reCAPTCHA, either you set a severe, forceful and unshakable norm or will it be the death of this tool. I hope you can consider this request that would help the health of the internet. Thanks you so much.

**Comment by JReming85** [comment]
How exactly would this automation tool, security/load testing tool effect Google's reCaptcha and why would it even matter when we are only performing tests on our own systems or systems we have explicit permission to test?

**Comment by openbullet** [comment]
Sorry this is just not going to happen

**Comment by mastercho** [comment]
Its says on firsts lines

IMPORTANT! Performing (D)DoS attacks or credential stuffing on sites you do not own (or you do not have permission to test) is illegal! The developer will not be held responsible for improper use of this software.

Clearly you attempt to use on site which you do not own...

**Comment by atayseny** [comment]
Well, don't be naive, a lot of people are using this tool for dishonest activities.

**Comment by JReming85** [comment]
And there are many people using it for legitimate use cases. Just because there are a small subset of users misusing a tool does not mean you cripple the tool.

I mean you would stop people from sending/receiving email because some people use it to spam, or kill torrent because some people use it for piracy. There are many more users that use email for legitimate reasons, same with torrent like data backup, sync and propagation. 

There are also plenty of other tools that do the exact same as this one, they just are not as easy to use and/or high cost to get started.

**Comment by openbullet** [comment]
I just wanted to add, this is an open source software, it would literally take another developer 10 minutes to remove the limits and spread an unlimited build everywhere ^^
