### ISSUE TITLE
[Bug]: Captcha service AZcaptcha not correct request 

### ISSUE THREAD

**Issue by AZcaptcha** [openbullet/OpenBullet2#531]
### Version of the software

0.1.26

### Operating system

Windows 10

### Browser / Native

91

### What happened?

A bug happened!
Not send request to AZcaptcha.com website. all request send to 2captcha.

**Comment by openbullet** [comment]
OB uses the CaptchaSharp library to solve captchas so you should open the issue on the other repository, thank you
https://github.com/openbullet/CaptchaSharp

In addition, I have no api key to test this. Since you seem to be using the official AZCaptcha account, please send me a temporary key via email at `ruri (at) openbullet [dot] dev` so that I can properly debug the issue, thank you!

**Comment by AZcaptcha** [comment]
Please try api key nwytblzqfzhfnd346wkjvrxx2m8c9gyp

**Comment by openbullet** [comment]
@AZcaptcha I fixed the issue, the fix will be in the next version of OB2
