### ISSUE TITLE
[BUG] Parse Block Raising Errors

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#54]
**Describe the bug**
Can you make the parse block return empty instead of throwing an error.

Example:
Block:Parse
MODE:Json

if the site return a non json response, the parse block break and throw an error

**Comment by tcortega** [comment]
I honestly don't see any reasons for this to be implemented, once you can just handle the possible error. Ruri gave an example in this answer in another issue: https://github.com/openbullet/OpenBullet2/issues/12#issuecomment-793870899

**Comment by openbullet** [comment]
I can see why this would be preferred by non-programmers though.
We have to make a decision fast because if I do it, it will break configs that rely on catching the exception from the parse block, so it's better to do it as soon as possible instead of waiting to minimize the impact.

**Comment by tcortega** [comment]
> I can see why this would be preferred by non-programmers though.
> We have to make a decision fast because if I do it, it will break configs that rely on catching the exception from the parse block, so it's better to do it as soon as possible instead of waiting to minimize the impact.

I don't see why any configs would rely on catching the exception from the parse block, since the error handler is there because in `some cases` the error will happen. But if you want to implement this, its up to you, I personally see no reason to do this since you can easily use the TRY CATCH. That way new members/people not used to programming can also learn a bit more about programming and how to treat errors xD.

**Comment by openbullet** [comment]
Maybe we could set it to `null` instead of a blank string / empty list so we can differentiate between something that couldn't be parsed and something that could be parsed but was simply empty.
This will avoid the try/catch syntax in the config and still let people check if anything was parsed through a keycheck right after the parse block, which adds less noise to the code.

Let me know what you guys think!
