### ISSUE TITLE
Unable to properly make configs when using OB Authentication [sub-menus missing]

### ISSUE THREAD

**Issue by Nigel1992** [openbullet/OpenBullet2#547]
**Version of the software**
0.1.26 beta

**Operating system**
Windows 10

**Browser / Native**
Browser

**What happened?**
I am unable to create/edit a config because several sub-menus are missing.
![image](https://user-images.githubusercontent.com/5491930/141529790-c4ac2f13-0bb2-4d0c-843f-df301685c4fd.png)

**How to replicate this issue**
Set up admin authentication and log in.
Try to create/edit a config and you will see.

**Comment by openbullet** [comment]
This happens when using OB2 remotely because of some code that is executed too early, it's not a game breaking issue, just hit F5 and the submenu will show up. I will leave this open so I can take a look at it when I have time.

**Comment by Nigel1992** [comment]
> This happens when using OB2 remotely (especially if there is a high latency) because of some code that is executed too early, it's not a game breaking issue, just hit F5 and the submenu will show up. I will leave this open so I can take a look at it when I have time.

But why does it only happen when I use the login feature ?
Its working perfectly without the login.
Both remotely on an VPS using ngrok.

**Comment by openbullet** [comment]
Because the piece of code that handles whether a user has access to the config submenu (denying access to guests) has some logic that displays the submenu basing on the role of the authenticated user, and on remote it gets executed way too early, before the server can verify the jwt and read the actual role (admin / guest) you have. I just have to find a way to trigger it after authentication has already been verified. For now just use F5, I've had it happen before and it always worked after a refresh. If you feel like investigating the issue yourself feel free to submit a PR and I will review it!
