### ISSUE TITLE
[REQUEST] <DICT{key}>

### ISSUE THREAD

**Issue by qMMMp** [openbullet/OpenBullet2#55]
Can we have a block to get the value of a key from a Dictionary, like old <DICT{key}>

why ?
it would be very simple to have a block, like Get Key block in the dictionary functions section
a block that return empty incase the key does not exists in the dictionary

i know that there many ways around this, to get the same result. but incase those ways fail, they throw errors
like Block:constant String/int/... <DICT{key}>, it throws error incase there is no key
...

i know that we have try and catch
but most people users are not coders, and they never heard of try and catch
so, something simple would be very good

thanks

**Comment by openbullet** [comment]
To check if a dictionary has a certain key you can use a dictionary key (e.g. in keycheck block or in an IF statement) like
```
DICTKEY @dict HasKey "abc"
```

To have the value of a key you can use `dict["name"]`.

To have the KEY of a dictionary based on its value you can use the block under Functions > Dictionary Functions.

The fact is that since everything compiles down to C# I have to respect the language constructs and cannot do whatever I want like I was doing in OB1. Please adapt to the new changes, in the future I might consider an OB1-like mode where everything is a string and configs are interpreted at runtime.
