### ISSUE TITLE
[Bug]:  Always error 1000 and error 10100

### ISSUE THREAD

**Issue by gabriel9010** [openbullet/OpenBullet2#588]
### Version of the software

1.28

### Operating system

Debian11

### Browser / Native

FireFox

### What happened?

I always have the same error 1000 10100 can you help me????

**Comment by openbullet** [comment]
Do not open the same issue twice. It will not make me fix it sooner. https://github.com/openbullet/OpenBullet2/issues/564

**Comment by gabriel9010** [comment]
keep calm i'm informing you that there is always that problem. i will
tell you my friends not to use your apps anymore

**Comment by openbullet** [comment]
I'm calm, why don't you just comment on this issue https://github.com/openbullet/OpenBullet2/issues/483 instead of opening new ones? I'm well aware of this problem but since I am working a full time job and only coding OB2 in my free time, I cannot address everything immediately, especially this since it is an issue related to concurrent database access and it is hard to debug.

Also I really don't care if you don't want to use this application anymore. If you don't like it, use something else, you didn't pay anything it's a free software so you are not entitled to anything 😃
