### ISSUE TITLE
[Bug]: AddToList shows error when variable is a global list

### ISSUE THREAD

**Issue by APT-ZERO** [openbullet/OpenBullet2#589]
### Version of the software

0.1.28 [Beta]

### Operating system

Windows 10

### Browser / Native

Browser [Chrome/Firefox/Brave]

### What happened?

A bug happened!
AddToList shows error when variable is a global list
ERROR :
`[Executing block Add To List] RuntimeBinderException: 'System.Collections.Generic.List<string>' does not contain a definition for 'AsList'`

this problem fixed after i changed :
```
// BLOCK: Add To List
data.ExecutingBlock("Add To List");
AddToList(data, globals.mygloblist.AsList(), "a simple text", -1);
```
to
```
AddToList(data, globals.mygloblist, "a simple text", -1);
```

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
or maybe i should not use globals in blocks as variable?

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
there is many problem with globals in 0.1.28, idk it's only this version or all versions is like this
i can't use even lolicodes that you send in forum, like this one
```
TRY
IF BOOLKEY @globals.myglobvar Is true
JUMP #Continue
END
CATCH
END
```
but after i copied c# in lolicode and removed `.AsBool()` now it's ok
idk if it's a bug or no

**Comment by openbullet** [comment]
Hi, globals are dynamic behind the scenes, so that's why it has trouble with extension methods, it doesn't know the type at compile time so it cannot identify extension methods such as `AsList()`. I will add some code to explicitly cast the variable in case it's dynamic, and then call the extension method, that way it should work. (e.g. `((List<string>)globals.mygloblist).AsList()`) and you will still be able to cast from one type to another.

**Comment by openbullet** [comment]
Apparently this has already been solved a long time ago. Just tested and this works

```
BLOCK:ConstantList
  value = ["one", "two", "three"]
  => VAR @globals.myList
ENDBLOCK

BLOCK:AddToList
  list = @globals.myList
  item = "four"
ENDBLOCK

LOG @globals.myList
```

The call gets correctly converted to
```cs
AddToList(data, (List<string>)((object)globals.myList).DynamicAsList(), "four", -1);
```
