### ISSUE TITLE
Proxies unable to work on MacOS Monterey

### ISSUE THREAD

**Issue by anikait13** [openbullet/OpenBullet2#591]
Whenever i try to run a task. It goes through without using proxies but with them it never works. I have checked the proxies and the config, they work fine on windows but on just my Mac.
I think it might be a firewall MacOS or some permission related issue.
I ​would be grateful if anyone could assist me on this. Thanks!

**Comment by meinname** [comment]
🤔 copied over my ob2 to my new macbook and it works great here
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/16181408/148534496-b78578ea-c711-43c5-adad-3033868659c8.png">

if you have no 3rd Party Firewall or VPN or so i only could imagine that it could be because of openssl. 
Maybe install that with homebrew or so.
