### ISSUE TITLE
Releases with the same version

### ISSUE THREAD

**Issue by Obegg** [openbullet/OpenBullet2#632]
So, yesterday there was an update to 0.2.1, so I updated (using Native), now there's another update to 0.2.1, but Native doesn't see it. It's happened a few times now that there are a few releases with the same version, I understand that those are bug fixes, but the updater doesn't find them.

**Comment by openbullet** [comment]
Hello, those were fixed for people who couldn't open OB2 at all because of a bug in .NET desktop runtime v6.0.2 so we thought it was useless to push an update for everybody.

Turns out it's still broken though. Relevant forum post
https://discourse.openbullet.dev/t/i-am-getting-this-error-after-0-2-1-update/5332/12
