### ISSUE TITLE
Says this[Bug]: 

### ISSUE THREAD

**Issue by Sakoopa** [openbullet/OpenBullet2#647]
### Version of the software

newest

### Operating system

windows 10

### Browser / Native

native

### What happened?

![image](https://user-images.githubusercontent.com/80247735/156651773-724bf0b1-57cf-4b6c-81da-8de840a49e30.png)
it says this even tho i have installed it

**Comment by openbullet** [comment]
Since version 0.2.0 for OB2 you need to have .NET 6 installed. Maybe you have it but it's not at the latest version? I suggest downloading the SDK for .NET 6 since it has everything already included.

**Comment by JReming85** [comment]
You can try installing / reinstalling the 64 adn 32 bit versions

64bit - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer
32bit - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x86-installer

**Comment by Sakoopa** [comment]
@JReming85 i need them both?

**Comment by i6c** [comment]
@openbullet How do you install .net 6.0 SDK on ubuntu thoroughly ? I've been having to use beta version 0.1.26 instead of the latest , because 6.0 sdk seems like it doesnt want to work on Ubuntu , it tells me i have to install 6.0 sdk everytime even after i install it , and then i try to fix the code but then it just gives me attribute errors or etc,  help me out , please.

**Comment by i6c** [comment]
@Sakoopa obviously you dont need both youve never heard of x64 / x86? lol

**Comment by JReming85** [comment]
> @openbullet How do you install .net 6.0 SDK on ubuntu thoroughly ? I've been having to use beta version 0.1.26 instead of the latest , because 6.0 sdk seems like it doesnt want to work on Ubuntu , it tells me i have to install 6.0 sdk everytime even after i install it , and then i try to fix the code but then it just gives me attribute errors or etc, help me out , please.

You just need to run this script to install the SDK and can only be dont on current LTS versions and the latest 21.10

If your using 16.04, I am pretty sure its EOL later this year so might want to get it installed sooner then later and consider upgrading.

https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install

If you run it as root, it will work but will complain about using a sledgehammer to pound in a nail.

If you run it as another user, make sure the use has ownership and/or www-data is writable

**Comment by Sakoopa** [comment]
> @Sakoopa obviously you dont need both youve never heard of x64 / x86? lol
> 
> not to be rude but why are you enumerating when you don't even know basic computer knowledge?

I have them installed but it doesnt fucking work so im asking if i need them both because he linked them both.
yes i know what the difrence is so stfu

**Comment by JReming85** [comment]
> > @Sakoopa obviously you dont need both youve never heard of x64 / x86? lol
> > not to be rude but why are you enumerating when you don't even know basic computer knowledge?
> 
> I have them installed but it doesnt fucking work so im asking if i need them both because he linked them both. yes i know what the difrence is so stfu

Try opening Powershell or CMD and running 
`dotnet --list-runtimes`

Should output a list of all installed dotnet libs you have
(may be wrong but I think desktop installs all 3)
![image](https://user-images.githubusercontent.com/21246660/157922781-d58b5073-5baf-4188-9520-4074908c5ced.png)

You can also use `dotnet --list-sdks` for the SDK's
![image](https://user-images.githubusercontent.com/21246660/157923007-169fe8b4-5e6e-43bd-aabe-7ac9ecc19f4a.png)

 if you see it installed try using something like [Revo Uninstaller](https://www.revouninstaller.com/products/revo-uninstaller-free/) to completely remove it and reinstall.

Or reinstall it in Safe Mode, you can use [WinAero Tweaker](https://winaero.com/download-winaero-tweaker/) to enable installer in safe mod

Otherwise maybe check for windows updates and see if there is a security patch for it (doubt that would do anything)
SFC/Scannow
Checkdsk /F
or DISM /Online /Cleanup-Image /RestoreHealth

To repair windows to see if that helps.

**Comment by Sakoopa** [comment]
fixed
