### ISSUE TITLE
[Bug]: client crash

### ISSUE THREAD

**Issue by chekamarue** [openbullet/OpenBullet2#719]
### Version of the software

0.2.4

### Operating system

win 11

### Browser / Native

chrome 100

### What happened?

if the proxy mode is off and reload proxy value is set  ! the client crash right after reloading the proxies

easy to reproduce !

**Comment by openbullet** [comment]
As you can see from the code, proxies are reloaded only if `data.UseProxy` is true, otherwise it doesn't get into that part at all. Are you sure you didn't put something like `SET USEPROXY TRUE` in your config?

https://github.com/openbullet/OpenBullet2/blob/4e17b179accdee814bc22272cf6035739c93c625/RuriLib/Models/Jobs/MultiRunJob.cs#L215-L239

**Comment by opastorello** [comment]
The same happens with the native version, if the "Periodic reload interval" option is active the client closes.

**Comment by openbullet** [comment]
Closing stale issue
