### ISSUE TITLE
[Bug]: Can't mutate a variable that was taken from a resource

### ISSUE THREAD

**Issue by usdogu** [openbullet/OpenBullet2#806]
### Version of the software

0.2.4

### Operating system

Windows 8.1

### Browser / Native

Native

### What happened?

Creating a variable using a already existing variable name which was taken from resource fails because OB tries to create a new variable instead of mutating the existing one.

### Relevant LoliCode if needed

```shell
TAKEONE FROM "names" => @name

BLOCK:ToLowercase
LABEL:Name Lower
  input = @name
  => VAR @name
ENDBLOCK
```

**Comment by MajedurFahim** [comment]
> 
You dont have to do this :"TAKEONE FROM "names" => @name". Because Openbullet has wordlist system. You can add @name file in Wordlist. So just code to config like this

BLOCK:ToLowercase
LABEL:Name Lower
  input = @input.USER
  => VAR @@name
ENDBLOCK

Then just load you file in wordlist with right file type.
![image](https://user-images.githubusercontent.com/80979723/192119499-d8775258-a974-44ad-9230-d0ce0f0e15e8.png)

Then add a multi run and make a job and start. That's it.
![image](https://user-images.githubusercontent.com/80979723/192119339-2a16bf82-e4e7-4f91-a05c-9f15a2ea220c.png)

![image](https://user-images.githubusercontent.com/80979723/192119029-080ab791-397b-4a0c-8b99-caa9a04f85b8.png)

**Comment by openbullet** [comment]
Thank you for opening this issue, I will fix this. @MajedurFahim your answer does not really help with the exact problem that is described here, but thanks for helping anyways.
