### ISSUE TITLE
Variable connect bug

### ISSUE THREAD

**Issue by BHNHAT** [openbullet/OpenBullet2#90]
![image](https://user-images.githubusercontent.com/53633885/111026911-94c93900-841f-11eb-9741-dfae3bd91684.png)
It only hash `"<input.USER><MD5PASS>Mq7$LXmTW#YNjRmr"`
instead of `"SomeTextHere<input.USER><MD5PASS>Mq7$LXmTW#YNjRmr"`

**Comment by openbullet** [comment]
Thank you, this was a big game-breaking issue with ALL interpolated strings due to the recent changes to regex. I reverted the changes in https://github.com/openbullet/OpenBullet2/commit/7638becb6d0eb234bfd579cd82ef51cde6f5aaf3

I will push an urgent update and add some unit tests for this so it doesn't happen again in the future.

**Comment by openbullet** [comment]
Update 0.1.3 pushed, please everyone update your OB2 or most configs will not work.
