### ISSUE TITLE
[Bug]: Monitor not working

### ISSUE THREAD

**Issue by a9eesh** [openbullet/OpenBullet2#911]
### Version of the software

latest

### Operating system

Windows 10 Pro 22H2 (19045.3208)

### Browser / Native

Chrome 115.0.5790.110

### What happened?

I created a job and a proxy check and setup a monitor. 
I configured it that the job and proxy check stops after 15min.
Its at both not working.
I use the latest version and latest browser version (for me).

### Relevant LoliCode if needed

```shell
No code reveal cause it happens on both, proxy check and job run!
```

**Comment by openbullet** [comment]
Can you send a screenshot showing how you set up the triggered action in the job monitor please? Make sure it's set on greater or equal than 15 minutes (not equal) and make sure it's targeting the correct job and that the executions are 0, otherwise it won't get executed again. You can click on the reset button to reset the executions counter.

**Comment by openbullet** [comment]
Closing, stale issue
