### ISSUE TITLE
[REQUEST] How to avoid detection as a puppeteer?

### ISSUE THREAD

**Issue by Mejnun333** [openbullet/OpenBullet2#962]
How to avoid detection in Puppeteer? I'm getting detected all the time

**Comment by shaneilahi** [comment]
Its harder to be undetected since u dont have the source code of the puppeeter. But for minimal detections u can bypass via settubg random user agents. changing timezones based on IP (hard to do it but there some google extensions u can load and do it). randomizing viewport/window size. blocking web rtc leak etc.

**Comment by Mejnun333** [comment]
Yes, I tried it before but it is detected. Which google extensions do you recommend?

**Comment by openbullet** [comment]
Guys please use the [forum](https://discourse.openbullet.dev) for discussions
